name: Godot Export and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers the workflow on version tag pushes, e.g., v1.0.0
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  export-and-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Godot Exporter for Windows
      - name: Set up Godot Exporter for Windows
        uses: firebelley/godot-export@v6.0.0
        with:
             godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
             godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
             relative_project_path: ./

      # Create a GitHub Release and upload both Windows and Linux builds
      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       builds/Windows/*
      #       builds/Linux/*
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
      name: Release pushed tag
      runs-on: ubuntu-22.04
      steps:         
        - name: Create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ github.ref_name }}
          run: |
            gh release create "$GITHUB_REF_NAME" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
                --generate-notes
